knp_snappy:
  pdf:
    enabled: true
    binary: '%env(WKHTMLTOPDF_PATH)%'
    options:
      enable-local-file-access: true
  image:
    enabled: true
    binary: '%env(WKHTMLTOIMAGE_PATH)%'
    options: [ ]
