framework:
  messenger:

    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration

      async_tracking_delay:
        dsn: "doctrine://default"
        retry_strategy:
          max_retries: 0
        options:
          queue_name: "tracking-delay"
          unique_messages: "waiting_queue"

      # message in transport async_tracking_delay are rerouted to this queue
      # we declare it to get the waiting handler which retry to dispatch original message
      # see App\Messenger\TrackingDelay\CalculateTrackingDelayWaitingHandler
      async_tracking_delay_waiting:
        dsn: "doctrine://default"
        options:
          queue_name: "tracking-delay_waiting"
          unique_messages: "queue"

      async_dashboard_feeding:
        dsn: "doctrine://default"
        retry_strategy:
          max_retries: 0
        options:
          queue_name: "dashboard-feeding"
          unique_messages: true
    # Route your messages to the transports
    routing:
      App\Messenger\TrackingDelay\CalculateTrackingDelayMessage: async_tracking_delay
      App\Messenger\Dashboard\CalculateDashboardFeedingMessage: async_dashboard_feeding
      App\Messenger\Dashboard\CalculateLatePackComponentsMessage: async_dashboard_feeding
      App\Messenger\Dashboard\CalculateComponentsWithDelayMessage: async_dashboard_feeding

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
