framework:
  messenger:

    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration

      async_tracking_delay:
        dsn: "amqp://user1:pass1@mq-server:5672/%2f/user1-tracking_delay"
        options:
          queues:
            user1-tracking_delay:
              arguments:
                x-message-deduplication: true
        retry_strategy:
          max_retries: 0

      async_dashboard_feeding:
        dsn: "amqp://user1:pass1@mq-server:5672/%2f/dashboard-feeding"
        retry_strategy:
          max_retries: 0

    # Route your messages to the transports
    routing:
      App\Messenger\TrackingDelay\CalculateTrackingDelayMessage: async_tracking_delay
      App\Messenger\Dashboard\FeedDashboardComponentMessage: async_dashboard_feeding
      App\Messenger\Dashboard\FeedMultipleDashboardComponentMessage: async_dashboard_feeding

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
