framework:
  messenger:

    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async_tracking_delay:
        dsn: "doctrine://default"
        options:
          queue_name: "tracking-delay"
          unique_messages: true

    # Route your messages to the transports
    routing:
      App\Messenger\TrackingDelay\CalculateTrackingDelayMessage: async_tracking_delay

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
