nbgrp_onelogin_saml:
    onelogin_settings:
        default:
            # Mandatory SAML settings
            idp:
                entityId: 'http://fs.lyon.unicancer.fr/adfs/services/trust'
                singleSignOnService:
                    url: 'https://fs.lyon.unicancer.fr/adfs/ls/'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                singleLogoutService:
                    url: 'https://fs.lyon.unicancer.fr/adfs/ls/'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: 'MIIC5DCCAcygAwIBAgIQLE73hmxAcbBGhzGKzzreRjANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQDEyNBREZTIFNpZ25pbmcgLSBmcy5seW9uLnVuaWNhbmNlci5mcjAeFw0yMzA3MDgwMjA5MTZaFw0yNDA3MDcwMjA5MTZaMC4xLDAqBgNVBAMTI0FERlMgU2lnbmluZyAtIGZzLmx5b24udW5pY2FuY2VyLmZyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA561W7z2m3GBCs0qQizucWndwMN7PreKXIkXh4N6SSsUWFGjPJNhVUnxyLtxwNY6TBTYfhBWHWLcJqgQP5aE8ThnaQRpblyb0sUVmw7TzkFSgAB3Zs/0CFJ0WsWVlt3KyQl9tP5iFjKebQsKxO8EzvFNW2LzfzjgGCYhpj0L8uA9DhT5kDCo1u9svs6QtAqEQ63299oULdawCgmOXO45LdUFdBUFpxRgPibFXAepIVZSbX2aGw0K5e6v2bhH06rsrCcS2E5JbrneeDmbuuzRFkaXVE8gzzlYuXQsN5z613Efvk4pDBM6eo8Uut3QGObvE54p43IQQDKvshvZLCwikYQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCEw2sUk2Sv1joKnXMAc5+6i5Im58lmu2l1s78qyC3mMgBxZfdO41fqJsiFLxA+xQM/Oq5HU79ipiWNgDbcz076i5nySuC7Nw6ik3eWboh1+O94XDLUqXYkD2rWP5g3IIz1TJK/n6fVPKUM1vgbSmZrdwJe0knTTc6Yk2rGqTyL3o9UQMu+98YsOb+u+bSR82OzZOv/N7j2lMnigxqwYJDSTbdiVGpxLcuVAD42XNGnK20ShKYymglbd2IpU+o+BIOhOlqmsuEluFqmNGEsVdZKBxER2eHQV3IXqXbA604tTPllmvuGFSDgBbeG23BxaS+YmXFKrgdDoMAQmbpsdSnk'
            sp:
                entityId: '<request_scheme_and_host>/saml/metadata'
                assertionConsumerService:
                    url: '<request_scheme_and_host>/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                singleLogoutService:
                    url: '<request_scheme_and_host>/saml/logout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
