SELECT IF(worked_day.day = 'monday', 'lundi',
          IF(worked_day.day = 'tuesday', 'mardi',
             IF(worked_day.day = 'wednesday', 'mercredi',
                IF(worked_day.day = 'thursday', 'jeudi',
                   IF(worked_day.day = 'friday', 'vendredi',
                      IF(worked_day.day = 'saturday', 'samedi',
                         IF(worked_day.day = 'sunday', 'dimanche', NULL))))))) AS jour,
       IF(worked_day.worked = 1, 'oui', 'non')                                 AS travaille,
       IF(worked_day.times != '',
          IF(LOCATE(';', worked_day.times) > 0, SUBSTRING_INDEX(SUBSTRING_INDEX(worked_day.times, ';', 1), '-', 1),
             SUBSTRING_INDEX(worked_day.times, '-', 1)), NULL)                 AS horaire1,
       IF(worked_day.times != '',
          IF(LOCATE(';', worked_day.times) > 0, SUBSTRING_INDEX(SUBSTRING_INDEX(worked_day.times, ';', 1), '-', -1),
             SUBSTRING_INDEX(worked_day.times, '-', -1)), NULL)                AS horaire2,
       IF(LOCATE(';', worked_day.times) > 0, SUBSTRING_INDEX(SUBSTRING_INDEX(worked_day.times, ';', -1), '-', 1),
          NULL)                                                                 AS horaire3,
       IF(LOCATE(';', worked_day.times) > 0, SUBSTRING_INDEX(SUBSTRING_INDEX(worked_day.times, ';', -1), '-', -1),
          NULL)                                                                 AS horaire4

FROM worked_day
