name: build_dependencies_directories

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'
        branches:
            - 'WIIS-10930'

jobs:
    build_php_directories:
        runs-on: ubuntu-latest
        container:
            image: wiilog/wiistock-initializer:v1
            credentials:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PULL_TOKEN }}
            env:
                APP_ENV: prod
            options: --user root

        steps:
            -   name: go to project
                run: cd /project

            -   name: Checkout wiistock
                uses: actions/checkout@v4

            -   name: Install composer dependencies in app
                run: composer install

            -   name: install zip
                run: apk add zip

            -   name: zip vendor
                run: zip -r vendor.zip vendor

            -   name: Upload vendor
                uses: actions/upload-artifact@v2
                with:
                    name: vendor.zip
                    path: vendor.zip

            -   name: Upload vendor on the release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.WIISTOCK_ACCESS_TOKEN }}
                    file: vendor.zip
                    asset_name: vendor.zip
                    tag: ${{ github.ref }}

            -   name: Install build routing
                run: php bin/console fos:js-routing:dump --format=json --target=public/generated/routes.json

            -   name: Upload routes.json
                uses: actions/upload-artifact@v2
                with:
                    name: routes.json
                    path: routes.json

            -   name: Upload routes.json on the release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.WIISTOCK_ACCESS_TOKEN }}
                    file: routes.json
                    asset_name: routes.json
                    tag: ${{ github.ref }}
