name: build_dependencies_directories

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

jobs:
    build_php_directories:
        runs-on: ubuntu-latest
        container:
            image: wiilog/wiistock-initializer:v1
            credentials:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PULL_TOKEN }}
            env:
                APP_ENV: prod
            options: --user root

        steps:
            -   name: go to project
                run: mkdir /project && cd /project

            -   name: Checkout wiistock
                uses: actions/checkout@v4

            -   name: Install composer dependencies in app
                run: composer install --no-scripts

            -   name: install zip
                run: apk add zip

            -   name: zip vendor
                run: zip -r -y -qq vendor.zip vendor

            -   name: Upload vendor
                uses: actions/upload-artifact@v2
                with:
                    name: vendor.zip
                    path: vendor.zip

            -   name: Upload vendor on the release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.WIISTOCK_ACCESS_TOKEN }}
                    file: vendor.zip
                    asset_name: vendor.zip
                    tag: ${{ github.ref }}

            -   name: Add generated.yaml to wiistock
                run: |
                    touch config/generated.yaml &&
                    echo {"parameters": {"session_lifetime": 1440}} >> config/generated.yaml

            -   name: build routing
                run: php bin/console fos:js-routing:dump --format=json --target=public/generated/routes.json

            -   name: copy routes.json
                run: cp public/generated/routes.json routes.json

            -   name: Upload routes.json
                uses: actions/upload-artifact@v2
                with:
                    name: routes.json
                    path: routes.json

            -   name: Upload routes.json on the release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.WIISTOCK_ACCESS_TOKEN }}
                    file: routes.json
                    asset_name: routes.json
                    tag: ${{ github.ref }}

    build_js_directories:
        runs-on: ubuntu-latest
        container:
            image: wiilog/wiistock-initializer:v1
            credentials:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PULL_TOKEN }}
            env:
                APP_ENV: prod
            options: --user root

        steps:
            -   name: go to project
                run: mkdir /project && cd /project

            -   name: Checkout wiistock
                uses: actions/checkout@v4

            -   name: Install yarn dependencies in app
                run: yarn install

            -   name: install zip
                run: apk add zip

            -   name: zip node_modules
                run: zip -r -y -qq node_modules.zip node_modules

            -   name: Upload node_modules
                uses: actions/upload-artifact@v2
                with:
                    name: node_modules.zip
                    path: node_modules.zip

            -   name: Upload node_modules on the release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.WIISTOCK_ACCESS_TOKEN }}
                    file: node_modules.zip
                    asset_name: node_modules.zip
                    tag: ${{ github.ref }}
