name: run-cypress

on:
    push:
        branches:
            - WIIS-9654
        #pull_request:
        #    - todo

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        container:
            image: docker:latest
            options: --user 1000:1000
        steps:
            -   name: Checkout wiistock-docker
                uses: actions/checkout@v4
                with:
                    repository: wiilog/wiistock-docker
                    token: ${{ secrets.WIISTOCK_DOCKER_PULL_TOKEN }}

            -   name: Setup environment wiistock-docker
                run: cp .env.example .env

            -   name: Checkout wiistock
                uses: actions/checkout@v4
                with:
                    repository: wiilog/wiistock
                    #ref: ${{ github.event.pull_request.head.sha }}
                    ref: ${{ github.event.head_commit.id }}
                    path: projects/wiistock

            -   name: Copy .env.example to .env.local
                run: cp projects/wiistock/.env projects/wiistock/.env.local

            -   name: Change db string URL .env.local
                # todo : check if sed is working
                run: sed -i 's/root@127\.0\.0\.1:3306/root:example@mysql:3306/g' projects/wiistock/.env.local

            -   name: Add generated.yaml to wiistock
                run: |
                    touch projects/wiistock/config/generated.yaml &&
                    echo {"parameters": {"session_lifetime": 1440}} >> projects/wiistock/config/generated.yaml

            -   name: Build & run containers
                run: docker compose up --build -d app

            -   name: Install yarn dependencies in app
                run: docker exec wiistock_app yarn

            -   name: Down containers
                run: docker compose down

            -   name: Run cypress
                run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -p wiistock-cypress up cypress --abort-on-container-exit
