name: run-cypress

on:
   pull_request:
        branches:
             - "*"

concurrency:
    group: ${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        container:
            image: docker:latest
            options: --user root
        steps:
            -   name: Checkout wiistock-docker
                uses: actions/checkout@v4
                with:
                    repository: wiilog/wiistock-docker
                    token: ${{ secrets.WIISTOCK_DOCKER_PAT }} #Robin Personal Access Token available until Jan 1, 2025
                    ref: main

            -   name: Setup environment wiistock-docker
                run: cp .env.example .env

            -   name: Change  FTP credential in .env (FTP_HOST & FTP_USER & FTP_PASSWORD)
                run: |
                    sed -i "s/FTP_HOST=ftp\.wiilog\.fr/FTP_HOST=ftp:\/\/${{ secrets.WIISTOCK_DOCKER_FTP_HOST }}/g" .env
                    sed -i "s/FTP_USER=ftp/FTP_USER=${{ secrets.WIISTOCK_DOCKER_FTP_USER }}/g" .env
                    sed -i "s/FTP_PASSWORD=ftp/FTP_PASSWORD=${{ secrets. WIISTOCK_DOCKER_FTP_PASSWORD }}/g" .env

            -   name: Checkout wiistock
                uses: actions/checkout@v4
                with:
                    repository: wiilog/wiistock
                    ref: ${{ github.event.pull_request.head.sha }}
                    path: projects/wiistock

            #-   name: Login to docker hub
            #    run: docker login --username ${{ secrets.WIISTOCK_DOCKER_USER }} --password ${{ secrets.WIISTOCK_DOCKER_ACCESS_TOCKEN }}

            -   name: Copy .env to .env.local
                run: cp projects/wiistock/.env projects/wiistock/.env.local

            -   name: Change db string URL .env.local
                run: sed -i 's/root@127\.0\.0\.1:3306/root:example@mysql:3306/g' projects/wiistock/.env.local

            -   name: Change APP_ENV=prod to APP_ENV=dev
                run: sed -i 's/APP_ENV=prod/APP_ENV=dev/g' projects/wiistock/.env.local

            -   name: Add generated.yaml to wiistock
                run: |
                    touch projects/wiistock/config/generated.yaml &&
                    echo {"parameters": {"session_lifetime": 1440}} >> projects/wiistock/config/generated.yaml

            -   name: Give all right to wiistock
                run: chmod -R 777 projects/wiistock/

            -   name: Build & run containers
                run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -p wiistock-cypress up app --build -d

            -   name: Give right to www-data user
                run: docker exec wiistock-cypress_app chown -R www-data:www-data ./

            -   name: volume mount does not work on docker in docker so we manually copy the wiistoock
                run: docker cp projects/wiistock/. wiistock-cypress_app:/var/www/

            -   name: Install composer dependencies in app
                run: docker exec wiistock-cypress_app composer install

            -   name: Install yarn dependencies in app
                run: docker exec wiistock-cypress_app yarn

            -   name: Run cypress
                run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -p wiistock-cypress up cypress --exit-code-from cypress # --exit-code-from cypress : exit with the same code as cypress

            -   name: Copy logs, videos, and dev.log from the container # run only if cypress fail
                if: failure()
                run: |
                    docker cp wiistock_cypress:/var/www/cypress/logs/ cypress_logs
                    docker cp wiistock_cypress:/var/www/cypress/videos/ cypress_videos
                    docker cp wiistock_cypress:/var/www/var/log/dev.log dev_log

            -   name: Upload Cypress logs artifact # run only if cypress fail
                if: failure()
                uses: actions/upload-artifact@v2
                with:
                  name: cypress-logs
                  path: cypress_logs

            -   name: Upload Cypress videos artifact # run only if cypress fail
                if: failure()
                uses: actions/upload-artifact@v2
                with:
                  name: cypress-videos
                  path: cypress_videos

            -   name: Upload dev.log artifact # run only if cypress fail
                if: failure()
                uses: actions/upload-artifact@v2
                with:
                  name: dev-log
                  path: dev_log
