name: run-cypress

on:
    push:
        branches:
            - WIIS-9654
        #pull_request:
        #    - todo

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        container:
            image: docker:latest
            options: --user root
        steps:
            -   name: Checkout wiistock-docker
                uses: actions/checkout@v4
                with:
                    repository: wiilog/wiistock-docker
                    token: ${{ secrets.WIISTOCK_DOCKER_PULL_TOKEN }}
                    ref: WIIS-9654

            -   name: Setup environment wiistock-docker
                run: cp .env.example .env

            -   name: Change  FTP credential in .env (FTP_HOST & FTP_USER & FTP_PASSWORD)
                run: |
                    sed -i "s/FTP_HOST=ftp\.wiilog\.fr/FTP_HOST=ftp:\/\/${{ secrets.WIISTOCK_DOCKER_FTP_HOST }}/g" .env
                    sed -i "s/FTP_USER=ftp/FTP_USER=${{ secrets.WIISTOCK_DOCKER_FTP_USER }}/g" .env
                    sed -i "s/FTP_PASSWORD=ftp/FTP_PASSWORD=${{ secrets. WIISTOCK_DOCKER_FTP_PASSWORD }}/g" .env

            -   name: echo changes
                run: cat .env

            -   name: Checkout wiistock
                uses: actions/checkout@v4
                with:
                    repository: wiilog/wiistock
                    #ref: ${{ github.event.pull_request.head.sha }}
                    ref: ${{ github.event.head_commit.id }}
                    path: projects/wiistock

            -   name: Login to docker hub
                run: docker login --username ${{ secrets.WIISTOCK_DOCKER_USER }} --password ${{ secrets.WIISTOCK_DOCKER_ACCESS_TOCKEN }}

            -   name: Pull from dockerhub wiilog/wiistock-app
                run: docker pull wiilog/wiistock-app:latest

            -   name: Copy .env.example to .env.local
                run: cp projects/wiistock/.env projects/wiistock/.env.local

            -   name: Change db string URL .env.local
                run: sed -i 's/root@127\.0\.0\.1:3306/root:example@mysql:3306/g' projects/wiistock/.env.local

            -   name: Add generated.yaml to wiistock
                run: |
                    touch projects/wiistock/config/generated.yaml &&
                    echo {"parameters": {"session_lifetime": 1440}} >> projects/wiistock/config/generated.yaml

            -   name: Give right
                run: chmod -R 777 projects/wiistock/ # TODO: remove this line (pa bo grègwoêre a dit )

            -   name: Build & run containers
                run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -p wiistock-cypress up app --build -d
                # run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -p wiistock-cypress up app --build -d

            -   name: Give right
                run: docker exec wiistock-cypress_app chown -R www-data:www-data ./

            -   name: volume mount does not work on docker in docker so we manually copy the wiistoock
                run: docker cp projects/wiistock/. wiistock-cypress_app:/var/www/

            -   name: Install composer dependencies in app
                run: docker exec wiistock-cypress_app composer install

            -   name: Install yarn dependencies in app
                run: docker exec wiistock-cypress_app yarn

            -   name: Add FOS config
                run: docker exec wiistock-cypress_app php bin/console fos:js-routing:dump --format=json --target=public/generated/routes.json

            -   name: Run cypress
                #  run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -f docker-compose-cypress-actions.yml -p wiistock-cypress up cypress --abort-on-container-exit
                run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -p wiistock-cypress up cypress
                continue-on-error: true

            -   name: Copy the logs from the container to the folder cypress_logs
                run: docker cp wiistock_cypress:/var/www/cypress/logs/ cypress_logs

            -   name: Put the logs in the artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: cypress-logs
                    path: cypress_logs

            -   name: Copy the videos from the container to the folder cypress_videos
                run: docker cp wiistock_cypress:/var/www/cypress/videos/ cypress_videos

            -   name: Put the videos generated by cypress in the artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: cypress-videos
                    path: cypress_videos
